### ISSUE TITLE
How to get an API key?

### ISSUE THREAD

**Issue by maelle** [sckott/discgolf#10]
Could you add a bit more details? The API docs weren't clear enough for me: do I need to create a discourse account? Would I need to be an admin of discuss.ropensci.org?

**Comment by sckott** [comment]
looked like only admins could  get api keys - BUT saw this just now https://meta.discourse.org/t/user-api-keys-specification/48536 so looks like we can set that up probably on ropensci and see if it works

**Comment by maelle** [comment]
Putting it on the agenda for next call 😀
