### ISSUE TITLE
use paginator client?

### ISSUE THREAD

**Issue by maelle** [sckott/discgolf#11]
I'm working on my use cases collecting script. I would need to get all posts from a category and was wondering if by any chance you'd be willing to change things upstream to the following behavior :innocent: 

If `page=NULL`, fetch all pages?

No worries if not, in that case I'd update my script. :grin:

**Comment by sckott** [comment]
I'll take a look

**Comment by maelle** [comment]
Thank you :pray:

**Comment by sckott** [comment]
Discourse API has weird pagination. I added page/per_page pagination to crul Paginator https://github.com/ropensci/crul/issues/145 but then realized it won't work with Discourse API unless you know how many records total you want, and there's no API calls to get that in discourse API. 

So there's a custom pagination thing https://github.com/sckott/discgolf/blob/master/R/http.R#L85-L101 - just worked in to one function right now. `category_latest_topics(category="usecases", page = NULL)` . 

which fxn were you using?

**Comment by maelle** [comment]
I was using `category()`, but switched to `category_latest_topics()`, thank you! There are 32 topics at the moment but this number will increase so better be prepared.

Btw now that the use cases collection for the website depends on discgolf should this be moved to ropensci-org?

**Comment by maelle** [comment]
mmmh actually I get 32 but there are more :thinking:

**Comment by maelle** [comment]
oooh I see sorry the list is nested.

**Comment by maelle** [comment]
@sckott sorry but what is wrong with my code below, why do I only get 32 IDs?

``` r
usecases <- discgolf::category("usecases")
usecases_ids <- usecases$topic_list$topics$id
length(usecases_ids)
#> [1] 30
```

<sup>Created on 2020-09-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

<details style="margin-bottom:10px;">

<summary>Session info</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.0.2 (2020-06-22)
#>  os       Ubuntu 20.04.1 LTS          
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language (EN)                        
#>  collate  fr_FR.UTF-8                 
#>  ctype    fr_FR.UTF-8                 
#>  tz       Europe/Paris                
#>  date     2020-09-05                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date       lib source                            
#>  assertthat    0.2.1      2019-03-21 [3] CRAN (R 4.0.0)                    
#>  cli           2.0.2      2020-02-28 [3] CRAN (R 4.0.0)                    
#>  crayon        1.3.4      2017-09-16 [3] CRAN (R 4.0.0)                    
#>  crul          1.0.0      2020-07-30 [1] CRAN (R 4.0.2)                    
#>  curl          4.3        2019-12-02 [3] CRAN (R 4.0.0)                    
#>  digest        0.6.25     2020-02-23 [3] CRAN (R 4.0.0)                    
#>  discgolf      0.2.3.96   2020-09-05 [1] Github (sckott/discgolf@c683f2e)  
#>  evaluate      0.14       2019-05-28 [3] CRAN (R 4.0.0)                    
#>  fansi         0.4.1      2020-01-08 [3] CRAN (R 4.0.0)                    
#>  fs            1.5.0      2020-07-31 [3] CRAN (R 4.0.2)                    
#>  glue          1.4.2      2020-08-27 [1] CRAN (R 4.0.2)                    
#>  highr         0.8        2019-03-20 [3] CRAN (R 4.0.0)                    
#>  htmltools     0.5.0      2020-06-16 [3] CRAN (R 4.0.1)                    
#>  httpcode      0.3.0      2020-04-10 [1] CRAN (R 4.0.2)                    
#>  jsonlite      1.7.0      2020-06-25 [3] CRAN (R 4.0.2)                    
#>  knitr         1.29       2020-06-23 [3] CRAN (R 4.0.2)                    
#>  magrittr      1.5        2014-11-22 [3] CRAN (R 4.0.0)                    
#>  R6            2.4.1      2019-11-12 [3] CRAN (R 4.0.0)                    
#>  Rcpp          1.0.5      2020-07-06 [3] CRAN (R 4.0.2)                    
#>  reprex        0.3.0.9001 2020-08-19 [1] Github (tidyverse/reprex@23a3462) 
#>  rlang         0.4.7      2020-07-09 [3] CRAN (R 4.0.2)                    
#>  rmarkdown     2.3.3      2020-08-19 [1] Github (rstudio/rmarkdown@204aa41)
#>  sessioninfo   1.1.1      2018-11-05 [3] CRAN (R 4.0.0)                    
#>  stringi       1.4.6      2020-02-17 [3] CRAN (R 4.0.0)                    
#>  stringr       1.4.0      2019-02-10 [3] CRAN (R 4.0.0)                    
#>  triebeard     0.3.0      2016-08-04 [1] CRAN (R 4.0.2)                    
#>  urltools      1.7.3      2019-04-14 [1] CRAN (R 4.0.2)                    
#>  withr         2.2.0      2020-04-20 [3] CRAN (R 4.0.0)                    
#>  xfun          0.16       2020-07-24 [3] CRAN (R 4.0.2)                    
#>  xml2          1.3.2      2020-04-23 [3] CRAN (R 4.0.0)                    
#>  yaml          2.2.1      2020-02-01 [3] CRAN (R 4.0.0)                    
#> 
#> [1] /home/maelle/R/x86_64-pc-linux-gnu-library/4.0
#> [2] /usr/local/lib/R/site-library
#> [3] /usr/lib/R/site-library
#> [4] /usr/lib/R/library
```

</details>

**Comment by maelle** [comment]
Update: once I understood the list structure I got all the use cases there are, thanks again

**Comment by sckott** [comment]
glad it works!  I will add it to the rest of the functions if possible - its not always clear which support pagination, so that will take some poking around. 

yeah, prob. makes sense to move to ropensci org

**Comment by maelle** [comment]
Could it make sense to give feedback to Discourse directly reg API design?

**Comment by sckott** [comment]
true, could suggest bretter docs for pagination

**Comment by maelle** [comment]
or even easier pagination

**Comment by sckott** [comment]
Well i imagine the main use case is for web flow, so i could try but I imagine they want to optimize for webflow

**Comment by maelle** [comment]
I no longer get all topics via the function as it seems the API output slightly changed. However I'm not sure you're still maintaining this @sckott? (I can work around this, and your package is still very useful, thank you!)

**Comment by sckott** [comment]
No, i'm not maintaining it, but will leave the pkg here in case people want to use it. So close this then?
