### ISSUE TITLE
Search for topics with a given tag - page limitation

### ISSUE THREAD

**Issue by marionlouveaux** [sckott/discgolf#14]
Hi!

First, thank you for creating the discgolf package!
I am searching for topics on the [image.sc forum](https://forum.image.sc/) tagged with a given tag ("icy", the name of an image analysis software). I would like to get all topics (there are just over a hundred of them).

<details> <summary><strong>Session info and discgolf version</strong></summary>

discgolf      0.2.8.91 2021-02-19 [1] Github

```r
- Session info ------------------------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.2 (2020-06-22)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  French_France.1252          
 ctype    French_France.1252          
 tz       Europe/Paris                
 date     2021-02-22 
```
</details>

I tried to get "icy" topics using the dg_search() function, but it found only the 5 last topics tagged with "icy". I also tried the tag() function, but it only found the 30 latest topics. I managed with some help to get around these limitations by modifying the dg_search() function and get all the topics, but this is far from being optimal. I copy paste the code below in case someone else encounters a similar issue.

<details> <summary><strong>R code</strong></summary>

```r
# dg_search gives only the 5 last topics with the tag icy
test_query <- discgolf::dg_search(query = "tags:icy")
test_query$topics

# tag() gives access to the latest 30 topics only
all_tags <- discgolf:::tag("icy")
topics <- all_tags$topic_list$topics
nrow(topics)
# There is more than a hundred topics
all_tags$topic_list$tags


# modification of the dg_search() function
get_page <- function (url, verb, endpt, args = list(), body = list(), ...) 
{
  headers_auth <- list(`Api-Key` = discgolf:::check_key(),
                       `Api-Username` = discgolf:::check_user())
  cli <- crul::HttpClient$new(url = url, #as.url(check_url(), endpt), 
                              headers = c(discgolf:::dg_head(), headers_auth),
                              opts = list(...))
  res <- cli$get()
  # res <- switch(verb, GET = cli$get(query = args), 
  # POST = cli$post(query = args, 
  #            body = body), PUT = cli$put(query = args, body = body), 
  #               DELETE = cli$delete(query = args))
  res$raise_for_status()
  discgolf:::check_res(res)
  res_json <- discgolf:::parse_json(res)
  return(res_json)
}

# get topics tagged with "icy" on page number 1
url <- "https://forum.image.sc/search?q=tags%3Aicy order%3Alatest&page=1"
x <- get_page(url = url)
dim(x$topics)
tibble::as_tibble(x$topics)

# get topics tagged with "icy" on page number 2
url2 <- "https://forum.image.sc/search?q=tags%3Aicy order%3Alatest&page=2"
x2 <- get_page(url = url2)
dim(x2$topics)
tibble::as_tibble(x2$topics)
```
</details>

Could a future version of dg_search() take in account the page number?
More precisely, could dg_search() have an optionnal argument page that is added to the URL with the symbol &?

<details> <summary><strong>R code</strong></summary>

```r
# dg_search(query = "tags:icy", order = "latest", page = 1)
```
</details>

Many thanks in advance.

**Comment by sckott** [comment]
Thanks for the detailed issue! 

Sorry about the lack of pagination. The discourse API docs are better than they used to be - i used to have to look at their Ruby client to understand the API. At least now they have actual docs https://docs.discourse.org/ - But they still do not document how pagination should be performed on any of their routes so thats fun.

Nice work on sorting out your own solution.

**Comment by sckott** [comment]
Made a change to `dg_search`:

- changed API route from `/search/term` to `/search`
- query goes to `q` instead of `term`
- page now passed in to `&`

I couldn't find a parameter to limit how many results are returned, but at least `page` is there

**Comment by marionlouveaux** [comment]
I tested the new dg_search() version and it works well. Thank you!!

**Comment by sckott** [comment]
great! glad it works

**Comment by sckott** [comment]
let me know if there's other issues to address here. if not I'll close this

**Comment by marionlouveaux** [comment]
I don't see anything else to address here. You can close this issue.
Thank you!

**Comment by sckott** [comment]
okay, will do. thanks
